name: addToFile CI

on:
  push:
    paths:
      - 'src/addToFile.c'
  pull_request:
    paths:
      - 'src/addToFile.c'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install -y gcc
    - name: make
      run: gcc src/addToFile.c -o src/addToFile
    - name: run
      env:
        PRIMES_FILE_PATH: ./docs/test-pr.txt
      run: time ./src/addToFile