name: checkMultiPrimes CI

on:
  push:
    paths:
      - 'src/checkMultiPrimes.c'
  pull_request:
    paths:
      - 'src/checkMultiPrimes.c'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install -y gcc
    - name: make
      run: gcc src/checkMultiPrimes.c -o src/checkMultiPrimes
    - name: run
      run: |
        for i in {1..3}
        do
          echo "Run $i"
          timeout 2m time ./src/checkMultiPrimes || exit 1
        done