name: checkPrimes CI

on:
  push:
    paths:
      - 'src/checkPrimes.c'
  pull_request:
    paths:
      - 'src/checkPrimes.c'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install -y gcc
    - name: make
      run: gcc src/checkPrimes.c -o src/checkPrimes
    - name: run
      run: |
        echo "4611686014132420609" | time ./src/checkPrimes