name: createFileWithLimit CI

on:
  push:
    paths:
      - 'src/createFileWithLimit.c'
  pull_request:
    paths:
      - 'src/createFileWithLimit.c'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install -y gcc
    - name: make
      run: gcc src/createFileWithLimit.c -o src/createFileWithLimit
    - name: run
      env:
        PRIMES_FILE_PATH: ./docs/test-pr.txt
      run: |
        for i in {1..3}
        do
          echo "Run $i"
          timeout 2m time ./src/createFileWithLimit || exit 1
        done