name: genAndPrint CI

on:
  push:
    paths:
      - 'src/genAndPrint.c'
  pull_request:
    paths:
      - 'src/genAndPrint.c'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install -y gcc
    - name: make
      run: gcc src/genAndPrint.c -o src/genAndPrint
    - name: run
      run: time ./src/genAndPrint